setopt histignorealldups sharehistory

# Use modern completion system
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit


zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

setopt complete_aliases

set -o vi
fpath+=${ZDOTDIR:-~}/.zsh_functions

EDITOR=vi

# Make it so `command $foo` will potential split "$foo" into multiple
# parameters, which is how most other shells work.
setopt shwordsplit

# When a glob doesn't match anything, pass it through to the command unchanged.
# This is useful for remote globbing, e.g., rsync host:~/foo*.
setopt nonomatch

# Append to the history.
setopt appendhistory
# Use the extended history format, which gives timing info.
setopt extendedhistory
# Append to the history after each command runs, including timing info.
setopt incappendhistorytime
# Do not store adjacent duplicate commands.
setopt histignoredups
# Remove superfluous blanks that sometimes make it into my commands.
setopt histreduceblanks

# Set history file and limits. Make them huge.
HISTFILE=~/.zsh_history
HISTSIZE=100000000
SAVEHIST=100000000

export AUTO_TITLE_SCREENS="NO"

set-title() {
    echo -e "\e]0;$*\007"
}

ssh() {
    set-title $*;
    /usr/bin/ssh -2 $*;
    set-title $HOST;
}

prit() {
    local_branch="$(git rev-parse --abbrev-ref HEAD)"

    git push origin -f "$local_branch:$USER/$local_branch"
}

alias e=vim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/scripts
export PATH=$PATH:$HOME/.vim/plugged/fzf/bin
export PATH="$PATH:$HOME/.env/local/nvim-linux-x86_64/bin"
export PATH="$PATH:$HOME/.env/local/clangd_12.0.1/bin"

alias vi='nvim'
alias gpr="git pull --rebase"
alias gvv="git branch -vv"
alias gst="git status"
alias gca="git commit -a --amend"
alias gcad="git commit -a"
alias gco="git checkout"
alias gdf="git diff"
alias fo='vim $(fzf)'
alias tmux="tmux -2"

alias bb="bazel build --ui_event_filters=-info --disk_cache=/home/$USER/bazel-cache"
alias br="bazel run --ui_event_filters=-info --disk_cache=/home/$USER/bazel-cache"
alias bt="bazel test --ui_event_filters=-info --disk_cache=/home/$USER/bazel-cache"
alias bbo="bazel build -c opt --ui_event_filters=-info --disk_cache=/home/$USER/bazel-cache"
alias bro="bazel run -c opt --ui_event_filters=-info --disk_cache=/home/$USER/bazel-cache"
alias bto="bazel test -c opt --ui_event_filters=-info --disk_cache=/home/$USER/bazel-cache"
alias gd="cd $HOME/graphane/"
alias gw="cd $HOME/graphane-wip/"
alias gfix="bb --config=fix-format //... && br //:buildifier -- --mode=fix --lint=fix -r . && bb --config=precommit --keep_going //..."

#fpath=(~/.zsh/completion $fpath)
#autoload -Uz compinit && compinit -i

bindkey -v

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform



## this should be the last line!!
eval "$(starship init zsh)"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
